version: "3"

services:

  project_jax23_cuda:
      build:
        context: .
        dockerfile: Dockerfile
      privileged: true
      tty: true
      # network_mode: "host"
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ./:/home/RL
      environment:
        - DISPLAY=$DISPLAY
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
      runtime: nvidia  # not need maybe for display atleast
      deploy:
              resources:
                reservations:
                  devices:
                    - driver: nvidia
                      count: 1
                      capabilities: [gpu]
